name: "Commit generated C# code"

on:
  workflow_run:

jobs:

  commit-job:
    name: "Commit generated C# code"
    if: github.actor == 'dependabot[bot]' #DO NOT REMOVE THIS LINE: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v2 
        with:
          submodules: 'true'

      - name: "Download changes to commit"
        uses: actions/download-artifact@v1
        with:
          name: "bindgen-cs"
          path: "./"

      - name: "Add + commit + push (if necessary)"
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'lithiumtoast'
          author_email: 'lithiumtoast@users.noreply.github.com'
          message: "Update bindings"
