name: "Pull Request"

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - '**.md'

jobs:

  bindgen-job:
    name: "Bindgen"
    uses: "./.github/workflows/bindgen.yml"

  build-job:
    name: "Build"
    needs: [bindgen-job]
    uses: "./.github/workflows/build.yml"
